languageCode = "vi-vn"
title = "Honu.vn - Tra cứu Chỉ số Thần số học"

# directory(s) where your articles are located
mainSections = ["posts"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # change to false to disable inclusion of rawHTML and math functions
      xhtml = false
    [markup.goldmark.extensions]
      typographer = false

[params]
  description = "Honu có nghĩa là Horoscope & Numerology. Bạn có thể nhận ebook tử vi miễn phí tại Honu. Chúc bạn vui vẻ!"
  footer = 'Một sản phẩm của <a href="https://www.svcorp.vn" target="_blank">SVCorp</a>.'